name: "cloth-texture-refine"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "multiview-camera-cloth-datamodule"
data:
  train_downsample_resolution: 1
  eval_downsample_resolution: 1
  train_data_interval: 1
  eval_data_interval: 1
  dataroot: ???
  eval_width: 2048
  eval_height: 2048
  eval_camera_distance: 3
  eval_fovy_deg: 45.
  eval_elevation_deg: 5.
  n_views: 120

  multiview_RD:
    train_downsample_resolution: 1
    eval_downsample_resolution: 1
    train_data_interval: 1
    eval_data_interval: 1
    dataroot: ${data.dataroot}
    eval_width: 2048
    eval_height: 2048
    eval_camera_distance: 3
    eval_fovy_deg: 45.
    eval_elevation_deg: 5.
    n_views: 120

system_type: "humannorm-cloth-system"
system:
  asset:
    ck_path: [
      ""
    ]
    bbox_info: [
      [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
    ]
    # scale xyz; trans xyz
    name: [
      ""
    ]
  test_save_path: ???
  texture: true
  geometry_type: "tetrahedra-sdf-grid-cloth"
  geometry_convert_from: ???
  geometry_convert_inherit_texture: true
  geometry:
    test_save_path: ${system.test_save_path}
    radius: 1.0 # consistent with coarse
    isosurface_resolution: "cube:256"
    isosurface_deformable_grid: false
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.4472692374403782 # max resolution 4096
    n_feature_dims: 3 # albedo3 + roughness1 + metallic1 + bump3
    fix_geometry: true

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "solid-color-background"
  background:
    n_output_dims: 3
    color: [1, 1, 1]

  renderer_type: "nvdiff-rasterizer-multiasset"
  renderer:
    use_sdf_loss: false
    context_type: cuda
    normal_type: 'camera'

  renderer_RD_type: "nvdiff-rasterizer-RD"
  renderer_RD:
    context_type: "cuda"
    camera_space: False
    mv_bg_colors: 'white'
    sd_bg_colors: 'white'

  exporter_type: "mesh-exporter"
  exporter:
    fmt: "obj"
    save_flag: false

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "./pretrained_models/normal-aligned-sd1.5"
    prompt: ???
    ori_prompt: ""
    front_threshold: 45.
    back_threshold: 45.
    human_part_prompt: false

  guidance_type: "sds-du-controlnet-guidance"
  guidance:
    pretrained_model_name_or_path: "./pretrained_models/normal-aligned-sd1.5"
    min_step_percent: [5000, 0.5, 0.5, 10000]
    max_step_percent: [5000, 0.51, 0.51, 10000]
    control_type: 'input_normal'
    controlnet_name_or_path: './pretrained_models/controlnet-normal-sd1.5'
    condition_scale: 1.0
    guidance_scale: 7.5
    per_editing_step: 10
    # canny_lower_bound: 120
    # canny_upper_bound: 150

  prompt_processor_RD_StableDiffusion_type: "stable-diffusion-prompt-processor-RD"
  prompt_processor_RD_StableDiffusion:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    negative_prompt: "shadow, oversaturated, low quality, unrealistic"

  guidance_RD_StableDiffusion_type: "stable-diffusion-dreamtimes-guidance"
  guidance_RD_StableDiffusion:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    min_step_percent: [5000, 0.5, 0.5, 10000] # (start_iter, start_val, end_val, end_iter)
    max_step_percent: [5000, 0.51, 0.51, 10000]
    guidance_scale: 50.
    use_sds: false
    per_editing_step: 10
    weighting_strategy: fantasia3d # default

  prompt_processor_RD_Albedo_type: "stable-diffusion-prompt-processor-RD"
  prompt_processor_RD_Albedo:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: "the albedo of ${system.prompt_processor_RD_StableDiffusion.prompt}"
    negative_prompt: "shadow"
    front_threshold: 30.
    back_threshold: 30.

  guidance_RD_Albedo_type: "nd-mv-dmtet-cat-guidance"
  guidance_RD_Albedo:
    model_name: "albedo-mv"
    ckpt_path: "pretrained_models/Damo_XR_Lab/Normal-Depth-Diffusion-Model/albedo_mv_ema.ckpt" # path
    cond_method: 'cat_d'
    guidance_scale: 10
    min_step_percent: [5000, 0.5, 0.5, 10000]  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: [5000, 0.51, 0.51, 10000]
    # weighting_strategy: fantasia3d
    # recon_loss: False
    recon_loss: True
    recon_std_rescale: 0.5
    use_sds: false
    per_editing_step: 10
    weighting_strategy: fantasia3d
    collect_inputs: ['albedo', 'mv_disparity']

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_sds: 0.
    lambda_l1: 1.
    lambda_p: 1.
    lambda_sds_RD_StableDiffusion: 0.
    lambda_l1_RD_StableDiffusion: 0.
    lambda_p_RD_StableDiffusion: 0.
    lambda_sds_RD_Albedo: 0.
    lambda_l1_RD_Albedo: 0.
    lambda_p_RD_Albedo: 0.

  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.001
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001
      asset_geometry_list:
        lr: 0.001

trainer:
  max_steps: 1000
  log_every_n_steps: 1
  num_sanity_val_steps: 120
  val_check_interval: 200
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
