name: "cloth-geometry"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-cloth-datamodule"
data:
  batch_size: 1
  width: 512
  height: 512
  camera_distance_range: [3, 3.5]
  fovy_range: [40, 45]
  elevation_range: [-10, 10]
  azimuth_range: [-180, 180]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_width: 2048
  eval_height: 2048
  eval_camera_distance: 3
  eval_fovy_deg: 45.
  eval_elevation_deg: 5.
  n_val_views: 120
  sampling_type: "full_body"
  fullbody_part_ratio:
    step: [0]
    ratio: [[1.0, 0.0, 0.0, 0.0]]
    # full\head\upper body\lower body
  sim_flag: true
  RD_prob: 0.5

  multiview_RD_flag: true
  multiview_RD:
    batch_size: 8
    width: 512
    height: 512
    camera_distance_range: [0.8, 1.0] 
    fovy_range: [40, 45]
    camera_perturb: 0.0
    center_perturb: 0.
    up_perturb: 0.
    elevation_range: [5, 30]
    azimuth_range: [-180, 180]
    batch_uniform_azimuth: true
    eval_width: 2048
    eval_height: 2048
    eval_camera_distance: 0.9
    eval_fovy_deg: 45.
    train_max_step: ${trainer.max_steps}
    train_val_check: ${trainer.val_check_interval}
    seed: ${seed}
    multiview_eval: true
    camera_sampling_stone: []
    cond_view: []
    relative: true

system_type: "humannorm-cloth-system"
system:
  asset:
    ck_path: [
      ""
    ]
    bbox_info: [
      [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
    ]
    # scale xyz; trans xyz
    name: [
      ""
    ]
  cloth:
    bbox_info: [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
    # [0.2, 0.3, 0.2, 0.0, 0.0, -1.0] shoe
    # [0.2, 0.2, 0.2, 0.0, 0.0, 0.8] cap
    # [0.3, 0.5, 0.3, 0.0, 0.0, 0.3] top
    # [0.5, 0.5, 0.5, 0.0, 0.0, -0.5] bottom
    # scale xyz; trans xyz
  RD:
    latent_steps: 1500
  test_save_path: ???
  start_sdf_loss_step: 3000
  geometry_type: "implicit-sdf-cloth"
  geometry:
    test_save_path: ${system.test_save_path}
    smplx_path: "./load/smplx_models"
    gender: "neutral"
    start_temp_loss_step: 0
    update_temp_loss_step: 1000000
    radius: 1
    n_feature_dims: 0
    isosurface_resolution: "cube:256"
    isosurface_deformable_grid: false
    isosurface_coarse_to_fine: false
    use_sdf_loss: false
    start_sdf_loss_step: ${system.start_sdf_loss_step}
    progressive_resolution: 
      step: [30000]
      resolution: [256]
    pos_encoding_config:
      otype: ProgressiveBandHashGrid # use progressive positional encoding
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378
      start_level: 8 # resolution ~200
      start_step: 500
      update_steps: 500
    # pos_encoding_config:
    #   otype: HashGrid
    #   n_levels: 16
    #   n_features_per_level: 2
    #   log2_hashmap_size: 19
    #   base_resolution: 16
    #   per_level_scale: 1.447269237440378
    # initialize SDF using a guide mesh
    shape_init: "ellipsoid"
    shape_init_params: [0.5, 0.5, 0.5]

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused
  background:
    n_output_dims: 3
    color: [1, 1, 1]

  renderer_type: "nvdiff-rasterizer-multiasset"
  renderer:
    use_sdf_loss: ${system.geometry.use_sdf_loss}
    context_type: cuda
    normal_type: 'camera'

  renderer_RD_type: "nvdiff-rasterizer-RD"
  renderer_RD:
    context_type: "cuda"
    camera_space: true
    mv_bg_colors: 'blue'
    sd_bg_colors: 'white'

  exporter_type: "mesh-exporter"
  exporter:
    fmt: "obj"
    save_flag: false

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "./pretrained_models/normal-adapted-sd1.5"
    prompt: ???
    ori_prompt: ""
    front_threshold: 45.
    back_threshold: 45.
    human_part_prompt: true

  prompt_processor_type_add: "stable-diffusion-prompt-processor"
  prompt_processor_add:
    pretrained_model_name_or_path: "./pretrained_models/depth-adapted-sd1.5"
    prompt: ???
    ori_prompt: ""
    front_threshold: 45.
    back_threshold: 45.
    human_part_prompt: true

  guidance_type: "sds-du-guidance" # normal sds
  guidance:
    pretrained_model_name_or_path: "./pretrained_models/normal-adapted-sd1.5"
    use_sds: true
    guidance_scale: 50 # diversity
    min_step_percent: [10000, 0.02, 0.02, 10001] # growing
    max_step_percent: [10000, 0.80, 0.21, 10001] # growing
    per_editing_step: -1 # unused

  guidance_type_add: "sds-du-guidance" # depth sds
  guidance_add:
    pretrained_model_name_or_path: "./pretrained_models/depth-adapted-sd1.5"
    use_sds: true
    guidance_scale: 50 # diversity
    min_step_percent: [5000, 0.02, 0.02, 8001] # growing
    max_step_percent: [5000, 0.81, 0.11, 8001] # growing
    per_editing_step: -1 # unused

  prompt_processor_RD_StableDiffusion_type: "stable-diffusion-prompt-processor-RD"
  prompt_processor_RD_StableDiffusion:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    negative_prompt: "low quality"

  guidance_RD_StableDiffusion_type: "stable-diffusion-dreamtimes-guidance"
  guidance_RD_StableDiffusion:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    min_step_percent: [0, 0.50, 0.02, 1500]  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: [0, 0.98, 0.50, 1500]
    guidance_scale: 50.
    weighting_strategy: fantasia3d

  prompt_processor_RD_NormalDepth_type: "stable-diffusion-prompt-processor-RD"
  prompt_processor_RD_NormalDepth:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5" # our model training
    prompt: ${system.prompt_processor_RD_StableDiffusion.prompt}
    negative_prompt: ${system.prompt_processor_RD_StableDiffusion.negative_prompt}
    front_threshold: 30.
    back_threshold: 30.

  guidance_RD_NormalDepth_type: "nd-mv-dmtet-guidance"
  guidance_RD_NormalDepth:
    model_name: "nd-mv"
    ckpt_path: 'pretrained_models/Damo_XR_Lab/Normal-Depth-Diffusion-Model/nd_mv_ema.ckpt'
    guidance_scale: 50
    min_step_percent: [0, 0.50, 0.02, 1500]  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: [0, 0.98, 0.50, 1500]
    # weighting_strategy: fantasia3d
    # recon_loss: false
    recon_loss: true
    recon_std_rescale: 0.5
    weighting_strategy: fantasia3d

  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_sds: 1.
    lambda_sds_add: [6000, 1., 0, 6001] 
    lambda_sds_RD_StableDiffusion: 1.
    lambda_sds_RD_NormalDepth: 1.
    lambda_sdf: 0
    lambda_normal_consistency: 1000 
    lambda_laplacian_smoothness: 0
    lambda_temp: 1000.
    lambda_msdf_temp: 0.
    lambda_collision: 0.
    lambda_l1: 0.
    lambda_p: 0.

  optimizer:
    name: AdamW
    args:
      lr: 0.00002
      betas: [0.9, 0.99]
      eps: 1.e-15
  
trainer:
  max_steps: 5000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 1000
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
